name: Build and Release for Multiple Platforms

on:
  push:
    branches:
      - main
    # tags:
    #   - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Go Project for Multiple Platforms
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Build
        run: |
          echo "Building for OS: ${{ matrix.os }}, Arch: ${{ matrix.arch }}"
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} CGO_CFLAGS="-Wno-deprecated-declarations" go build -o go-agent-${{ matrix.os }}-${{ matrix.arch }} cmd/main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-agent-${{ matrix.os }}-${{ matrix.arch }}
          path: go-agent-${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Create Release with Binaries
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && contains(github.ref, 'main')

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./ # Downloads all artifacts
        
      - name: Rename file 
        run: | 
          mv go-agent-windows-amd64/go-agent-windows-amd64 go-agent-windows-amd64/go-agent-windows-amd64.exe
          mv go-agent-windows-arm64/go-agent-windows-arm64 go-agent-windows-arm64/go-agent-windows-arm64.exe

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::AgentBuild_$(date +"%Y.%m.%d_%H-%M")"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          files: |
            go-agent-windows-amd64/go-agent-windows-amd64.exe
            go-agent-linux-amd64/go-agent-linux-amd64
            go-agent-windows-arm64/go-agent-windows-arm64.exe
            go-agent-linux-arm64/go-agent-linux-arm64
          draft: false # Set to true if you want to create the release as a draft first
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
